---
version: "3"
services:
  web:
    build: web
    ports:
      - 5555:8888
    depends_on:
      - api
  api:
    build: api
    ports:
      - 8888:8888
    depends_on:
      - feeder
      - user
  db:
    image: mongo
    volumes:
      - /home/micah/db:/data/db
  feeder:
    build: feeder
    depends_on:
      - broker
      - db
  broker:
    build: broker
    ports:
      - 1882:8888
  user:
    build: user
    depends_on:
      - db
  #notify:
  #  build: notify
  logger:
    build: logger
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  #admin:
  #  build: admin
  
