---
version: "3"
services:
  web-service:
    build: web
    ports:
      - 5555:9999
    depends_on:
      - api-service
  api-service:
    build: api
    ports:
      - 8888:8888
    depends_on:
      - feeder-service
      - user-service
  db:
    image: mongo
    volumes:
      - /home/micah/db:/data/db
  feeder-service:
    build: feeder-service
    depends_on:
      - broker
      - db
  broker:
    build: broker
    ports:
      - 1882:1883
      - 8882:8883
  user-service:
    build: user-service
    depends_on:
      - db

  
