---
version: "3"
services:
  web:
    build:
      context: web
      dockerfile: Dockerfile.dev
    links:
      - api:api
      - db:db
    ports:
      - 5555:9999
    volumes:
      - ./web:/app
  api:
    build:
      context: api
      dockerfile: Dockerfile.dev
    links:
      - controller:controller
      - db:db
    volumes:
     - ./api:/app
  db:
    image: mongo
    volumes:
      - ./db:/data/db
  controller:
    build:
      context: controller
      dockerfile: Dockerfile.dev
    links:
      - db:db
      - broker:broker
    volumes:
     - ./controller:/app
    
  broker:
    build: broker
    ports:
      - 1882:1883
      - 8882:8883
  
